### PR TITLE
Improved README: Added TOC, and split documentation to separate docs

### PR DESCRIPTION
**Pull request by leoloso**
As requested by @szepeviktor here: https://github.com/leoloso/PoP/issues/619#issuecomment-821841493

### CODE REVIEW

**Comment by leoloso** [comment]
@szepeviktor How do you like it now?

Check: https://github.com/leoloso/PoP/blob/3e2fee4a496bce85d6bdce59c03f7fedb3564271/README.md

**Comment by leoloso** [comment]
Updated version: https://github.com/leoloso/PoP/blob/77af547f1967c7b276a1714009f45adfb9f8d7ab/README.md

**Comment by szepeviktor** [comment]
It's time to found the Losoviz University 👨‍🎓 as the level of entry to PoP is so high.

**Comment by leoloso** [comment]
So, you approve this PR? Waiting for your confirmation to merge it

**Comment by szepeviktor** [comment]
Please merge it without me. I really do not know what to do with your project. It provides so many things like Laravel and Symfony combined.

**Pull request merged**
